#!/bin/bash
# Get the PID of the currently running intranet and kill it. If it is not running then it won't do anything.
cat /srv/hackerman/intranet/intranet.PIDFile > $intranetPID
kill $intranetPID > /dev/null 2>&1
# Remove all remainants of the intranet.
rm -rf /srv/intranet
# Clone the intranet to /srv/intranet
cd /srv/
git clone https://github.com/DamionGans/MegaMaxCorpinc-Intranet.git intranet
# Install the intranet package
cd intranet
npm install